DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS Currencies;

CREATE TABLE Currencies(
    id INT PRIMARY KEY IDENTITY,
    currency VARCHAR(50) NOT NULL UNIQUE,
);

CREATE TABLE accounts (

    id BIGINT PRIMARY KEY IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,
    balance FLOAT NOT NULL,
    currency INT NOT NULL REFERENCES Currencies(id),
    transaction_time DATETIME NOT NULL
);

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE GET_ACCOUNTS
AS
BEGIN
    SET NOCOUNT ON;

    SELECT * FROM dbo.Accounts
END
GO
